include /usr/share/cibs/rules/deb.mk
include /usr/share/cibs/rules/archive.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk

summary := GNU patch
license := GPL
license-file := COPYING

prefix := /usr/gnu

name     := patch
home     := http://savannah.gnu.org/projects/$(name)
version  := 2.7.1
archive  := $(name)-$(version).tar.gz
download := ftp://ftp.gnu.org/gnu/$(name)/$(archive)
checksum := \
     md5:95dd8d7e41dcbcecdd5cd88ef915378d \
    size:1014347
